import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile, writeFile, mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { pathToFileURL } from 'node:url';
import { chromium } from 'playwright';
import { buildPortfolioDemo } from '../../scripts/lib/portfolio-v1.mjs';
import { renderPortfolioPage } from '../../scripts/lib/portfolio-v1-page.mjs';
import { createPortfolioPreview } from '../../scripts/portfolio-v1.mjs';

test('portfolio walkthrough stays local, retains drafts, and exports only entered judgments', async t => {
  const demo = buildPortfolioDemo();
  const server = createPortfolioPreview(renderPortfolioPage(demo), JSON.stringify(demo));
  await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
  const origin = 'http://127.0.0.1:' + server.address().port;
  t.after(() => new Promise(resolve => server.close(resolve)));
  const browser = await chromium.launch({ headless: true });
  t.after(() => browser.close());
  const context = await browser.newContext({ viewport: { width: 1280, height: 850 }, serviceWorkers: 'block' });
  const requests = [];
  const errors = [];
  await context.route('**/*', route => {
    const request = route.request();
    requests.push({ origin: new URL(request.url()).origin, method: request.method() });
    assert.equal(new URL(request.url()).origin, origin);
    assert.equal(request.method(), 'GET');
    return route.continue();
  });
  const page = await context.newPage();
  page.on('pageerror', error => errors.push(error.message));
  await page.goto(origin);
  const downloadButton = page.getByRole('button', { name: '내 판단 기록 내려받기' });
  assert.equal(await downloadButton.isDisabled(), true);
  assert.match(await page.locator('#panel-R1').innerText(), /22\.9 kV 이상[\s\S]*24 kV[\s\S]*조건 충족/);
  await page.getByLabel('확인한 근거와 적용 조건').fill('SYNTHETIC_BROWSER_TEST: KR, BASIC_DESIGN, voltage');
  await page.getByRole('button', { name: 'R2 · 근거 부족', exact: true }).press('Enter');
  assert.match(await page.locator('#panel-R2').innerText(), /확인되지 않음[\s\S]*승인된 최신 단선결선도/);
  assert.equal(await page.locator('#panel-R1').isVisible(), false);
  await page.getByRole('button', { name: 'R3 · 조건 불충족', exact: true }).click();
  assert.match(await page.locator('#panel-R3').innerText(), /33 kV 이상[\s\S]*조건 불충족/);
  assert.equal(await page.getByLabel('확인한 근거와 적용 조건').inputValue(), 'SYNTHETIC_BROWSER_TEST: KR, BASIC_DESIGN, voltage');
  assert.equal(await downloadButton.isDisabled(), true);
  await page.getByLabel('기록 구분').selectOption('OWNER_REPRODUCTION');
  await page.getByLabel('내 판단과 이유').fill('SYNTHETIC_BROWSER_TEST: no real human decision');
  await page.getByLabel('아직 확인할 것 · 사용 중 막힌 점').fill('SYNTHETIC_BROWSER_TEST: no human value evidence');
  const downloaded = page.waitForEvent('download');
  await downloadButton.click();
  const file = await downloaded;
  const dir = await mkdtemp(join(tmpdir(), 'portfolio-download-test-'));
  t.after(() => rm(dir, { recursive: true, force: true }));
  await file.saveAs(join(dir, 'record.json'));
  const record = JSON.parse(await readFile(join(dir, 'record.json'), 'utf8'));
  assert.equal(record.judgmentAndReason, 'SYNTHETIC_BROWSER_TEST: no real human decision');
  assert.equal(record.viewedRevisionAtExport, 'R3');
  assert.equal(record.demoSha256, demo.canonicalSha256);
  assert.equal(record.formalPilotContribution, false);
  assert.equal(record.authorship, 'SELF_REPORTED_NOT_VERIFIED');
  assert.equal(record.productionReady, false);
  assert.equal(Object.hasOwn(record, 'finalHumanDecision'), false);
  await page.getByLabel('내 판단과 이유').fill('SYNTHETIC_BROWSER_TEST: unsaved update');
  assert.match(await page.locator('#record-status').innerText(), /작성 중/);
  for (const width of [390, 320]) {
    await page.setViewportSize({ width, height: 844 });
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), true);
  }
  // The preview serves only its two in-memory artifacts, never repo files or mutations.
  assert.equal((await fetch(origin + '/package.json')).status, 404);
  assert.equal((await fetch(origin, { method: 'POST', body: 'test' })).status, 404);
  assert.equal((await fetch(origin + '/demo.json')).status, 200);
  assert.deepEqual(errors, []);
  assert.ok(requests.length > 0);
});

test('standalone portfolio HTML works offline without a server or external resources', async t => {
  const dir = await mkdtemp(join(tmpdir(), 'portfolio-offline-test-'));
  t.after(() => rm(dir, { recursive: true, force: true }));
  const demo = buildPortfolioDemo();
  const target = join(dir, 'portfolio.html');
  await writeFile(target, renderPortfolioPage(demo));
  const browser = await chromium.launch({ headless: true });
  t.after(() => browser.close());
  const context = await browser.newContext({ offline: true, serviceWorkers: 'block' });
  const page = await context.newPage();
  const errors = [];
  const externalRequests = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('request', request => {
    if (/^https?:/.test(request.url())) externalRequests.push(request.url());
  });
  await page.goto(pathToFileURL(target).href);
  await page.getByRole('button', { name: 'R2 · 근거 부족', exact: true }).click();
  assert.match(await page.locator('#panel-R2').innerText(), /INSUFFICIENT_EVIDENCE/);
  await page.getByRole('button', { name: 'R3 · 조건 불충족', exact: true }).click();
  assert.match(await page.locator('#panel-R3').innerText(), /33 kV 이상[\s\S]*NOT_FIT/);
  await page.getByLabel('기록 구분').selectOption('OWNER_REPRODUCTION');
  await page.getByLabel('확인한 근거와 적용 조건').fill('SYNTHETIC_BROWSER_TEST: offline evidence check');
  await page.getByLabel('내 판단과 이유').fill('SYNTHETIC_BROWSER_TEST: offline test only');
  await page.getByLabel('아직 확인할 것 · 사용 중 막힌 점').fill('SYNTHETIC_BROWSER_TEST: human rehearsal pending');
  const downloadEvent = page.waitForEvent('download');
  await page.getByRole('button', { name: '내 판단 기록 내려받기' }).click();
  const downloaded = await downloadEvent;
  const output = join(dir, 'record.json');
  await downloaded.saveAs(output);
  const record = JSON.parse(await readFile(output, 'utf8'));
  assert.equal(record.viewedRevisionAtExport, 'R3');
  assert.equal(record.demoSha256, demo.canonicalSha256);
  assert.equal(record.judgmentAndReason, 'SYNTHETIC_BROWSER_TEST: offline test only');
  assert.equal(record.formalPilotContribution, false);
  assert.deepEqual(errors, []);
  assert.deepEqual(externalRequests, []);
});

test('agent walkthrough records cannot be mistaken for a human participant', async t => {
  const demo = buildPortfolioDemo();
  const server = createPortfolioPreview(renderPortfolioPage(demo), JSON.stringify(demo));
  await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
  t.after(() => new Promise(resolve => server.close(resolve)));
  const browser = await chromium.launch({ headless: true });
  t.after(() => browser.close());
  const page = await browser.newPage();
  await page.goto('http://127.0.0.1:' + server.address().port);
  assert.equal(await page.getByRole('option', { name: '에이전트 사용성 시뮬레이션', exact: true }).count(), 1);
  await page.getByLabel('기록 구분').selectOption('AGENT_SIMULATION');
  await page.getByLabel('확인한 근거와 적용 조건').fill('합성 R1/R2/R3와 KR 적용 범위를 확인한 에이전트 테스트');
  await page.getByLabel('내 판단과 이유').fill('R1 전압 조건 충족, R2 확인 보류, R3 현재 후보 제외');
  await page.getByLabel('아직 확인할 것 · 사용 중 막힌 점').fill('실제 사람의 평가와 실제품 사양 확인은 미수행');
  const event = page.waitForEvent('download');
  await page.getByRole('button', { name: '시뮬레이션 기록 내려받기', exact: true }).click();
  const downloaded = await event;
  assert.equal(downloaded.suggestedFilename(), 'b2b-portfolio-agent-simulation.json');
  const dir = await mkdtemp(join(tmpdir(), 'portfolio-agent-test-'));
  t.after(() => rm(dir, { recursive: true, force: true }));
  await downloaded.saveAs(join(dir, 'record.json'));
  const record = JSON.parse(await readFile(join(dir, 'record.json'), 'utf8'));
  assert.equal(record.recordKind, 'AGENT_SIMULATION');
  assert.equal(record.authorship, 'AI_AGENT_SIMULATION');
  assert.equal(record.humanParticipant, false);
  assert.equal(record.formalPilotContribution, false);
  assert.equal(record.productionReady, false);
  assert.equal(record.judgmentAndReason, 'R1 전압 조건 충족, R2 확인 보류, R3 현재 후보 제외');
});
